# Generated by Django 3.0.6 on 2020-05-31 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todoitem',
            name='due_date',
        ),
        migrations.AddField(
            model_name='todoitem',
            name='time',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
